version: '3'
services:
    # SSL対応
    https-portal:
        image: steveltn/https-portal:1
        container_name: "${HTTPS_PORTAL_CONTAINER_NAME}"
        ports:
        - "${LOCAL_SERVER_HTTP_PORT}:80"
        - "${LOCAL_SERVER_HTTPS_PORT}:443"
        depends_on:
        - nginx
        restart: on-failure:5
        volumes:
        - ./certs:/var/lib/https-portal
        environment:
    # 本番運用するときはコメントアウトを外してください
    #      STAGE: 'production'
            DOMAINS: >-
                ${YOUR_DOMAINS} -> http://nginx
            WORKER_PROCESSES: auto
            WORKER_CONNECTIONS: 2048
            CLIENT_MAX_BODY_SIZE: 128M

    # Nginx
    nginx:
        image: nginx:stable
        container_name: "${NGINX_CONTAINER_NAME}"
        restart: on-failure:5
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/log:/var/log/nginx
        - ./nginx/www:/var/www
        depends_on:
        - wordpress

    # MySQL
    mysql:
        image: mysql:5.7
        container_name: "${MYSQL_CONTAINER_NAME}"
        command:
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
        #コンテナ内のDBに外部からアクセスする必要がない場合はコメントアウト
        ports:
            - "${LOCAL_DB_PORT}:3306"
        restart: on-failure:5
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"


    # WordPress+PHP7.4
    wordpress:
        image: wordpress:php7.4-apache
        container_name: "${WORDPRESS_CONTAINER_NAME}"
        depends_on:
        - mysql
        restart: on-failure:5
        volumes:
            - ./wordpress:/var/www/html
            - ./wordpress-php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
            WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
